### ISSUE TITLE
Squeeze-cli - sqz serve (livereload module dependency is missing)

### ISSUE THREAD

**Issue by aymanshabarowork** [SqueezerIO/squeezer#49]
Bug Report Template -----------------------------------------------

##### Squeezer Framework Version information ( `squeezer-cli version` ) :

* Squeezer CLI version: v1.1.14
* Node version: v6.11.5
* OS platform: darwin

##### Expected Behavior:
$ sqz serve 
start the server

##### Actual Behavior:

Error: Cannot find module 'livereload'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/squeezer-cli/lib/plugins/serve/lib/express/livereload.js:3:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/squeezer-cli/lib/plugins/serve/lib/express/index.js:13:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

I think this module must be added in sqz dependencies

**Comment by nick-csu** [comment]
@aymanshabarowork thanks for reporting . I will make a new release within next hour which will fix the issue .

**Comment by aymanshabarowork** [comment]
thanks. i solved the issue by adding livereload module globally

**Comment by nick-csu** [comment]
great @aymanshabarowork  , I will keep you informed anyway. the new release got major changes and the project structure  changed significantly

**Comment by aymanshabarowork** [comment]
![screen shot 2017-10-26 at 15 14 25](https://user-images.githubusercontent.com/9929436/32052310-8b66b770-ba60-11e7-8204-c9059c15e36f.png)

There is also another problem with serve command.

**Comment by nick-csu** [comment]
@aymanshabarowork yes, please ignore the current release , serve is an external plugin , so that changed too and works only with the v1.1.15 release .

**Comment by nick-csu** [comment]
I'll get the new released pushed to npm in moments ;)

**Comment by aymanshabarowork** [comment]
it's ok... no rush 😄  i was just testing out and encountered this

**Comment by nick-csu** [comment]
@aymanshabarowork please re-try when you get a chance, I've just released the fixed version
